---
pages:
- posts/apps4fashion-powers-dj-kygo.md
- posts/vingino-successfully-launches-b2b-web-portal.md
- posts/klerx-shoes-successfully-launches-b2b-web-shop.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: textarea
  name: Intro
  label: Ankeiler
  config:
    required: true
    wysiwyg: false
- type: file
  name: Image
  label: Background image
