---
pages:
- posts/dobotex-teams-up-with-colect.io-to-upgrade-their-mobile-order-entry.md
- posts/herzlich-wilkommen--to-fynch-hatton.md
- posts/colect.io-warmly-welcomes-footwear-brand-hinson.md
- posts/a-warm-welcome-to-whyred.md
- posts/klerx-shoes-successfully-launches-b2b-web-shop.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: textarea
  name: Intro
  label: Ankeiler
  config:
    required: true
    wysiwyg: false
- type: file
  name: Image
  label: Background image
